name: Java CI

on:
  push:
    branches:
    - master

jobs:
  Ubuntu:
    name: Run Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Print gradle
      run: |
        chmod +x gradlew
        ./gradlew --version
    - name: Test
      run: ./gradlew test
    - name: Clone Javadoc
      run: |
        git config --global user.email "nobody@ms-paint-i.de"
        git config --global user.name "GitHub Actions"
        git config core.autocrlf true
        mkdir pages
        cd pages
        git clone https://github.com/RubbaBoy/EmojIDE-javadocs .
        rm -rf *
        cd ../
    - name: Javadoc
      run: |
        ./gradlew javadoc
        cd build/docs
        mv javadoc/* ../../pages
        cd ../../pages
        echo "docs.xn--is8hfy.ws" > CNAME
    - name: Push Javadoc
      run: |
        git add .
        git commit -m "Update docs from RubbaBoy/EmojIDE"
        git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/RubbaBoy/EmojIDE-javadocs.git" master:master
